import type { Metadata } from "next";

import { gilroy } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`h-full antialiased ${gilroy.variable}`}>
      <body className={`min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
